name: Cross platform build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ${{ matrix.build.os }}
    strategy:
      fail-fast: false
      matrix:
        build: 
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install Python dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt update
            sudo apt install -y python3-pip procps
            python3 -m pip install psutil
            pip3 install matplotlib
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            python3 -m pip install psutil --break-system-packages
            pip3 install matplotlib --break-system-packages
          fi

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B ${{ steps.strings.outputs.build-output-dir }} \
            -DCMAKE_C_COMPILER=${{ matrix.build.c_compiler }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.build.cpp_compiler }} \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: bash
        run: |
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

      - name: Run
        shell: bash
        run: |
          python3 monitor.py --duration 30 --executable ./build/main --log-file monitor_output.txt
          python3 plot_log.py --log-file monitor_output.txt --output heap_plot.png

      - name: Upload heap fragmentation graphic
        uses: actions/upload-artifact@v4
        with:
          name: heap-fragmentation-plot-${{ matrix.build.cpp_compiler }}-${{ runner.os }}
          path: heap_plot.png
